### ISSUE TITLE
rocksdb-ycsb runtime error

### ISSUE THREAD

**Issue by Guhaiyan** [YosubShin/RocksDB-YCSB#2]
I downloaded the rocksdb-ycsb sourcecode and complie (javac) successfully, but when I run RocksDBYcsbBinding.class, it received the exception. The error infomation is as below:

OpenJDK 64-Bit Server VM warning: You have loaded library /tmp/librocksdbjni4385108840943718520.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Exception in thread "Thread-1" java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni4385108840943718520.so: /tmp/librocksdbjni4385108840943718520.so: invalid ELF header (Possible cause: endianness mismatch)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1968)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1893)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1854)
        at java.lang.Runtime.load0(Runtime.java:795)
        at java.lang.System.load(System.java:1062)
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:51)
        at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:50)
        at org.rocksdb.RocksDB.<clinit>(RocksDB.java:28)
        at org.rocksdb.Options.<clinit>(Options.java:17)
        at org.rocksdb.ycsb.RocksDBYcsbBinding.init(RocksDBYcsbBinding.java:29)
        at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:63)
        at com.yahoo.ycsb.ClientThread.run(Client.java:189)

I am not sure if the error is related to jar file in lib or my machine enviroment settings. Look forward to your quick response.

**Comment by chshaiiith** [comment]
Hello @Guhaiyan ! were you able to resolve the issue ? I am stuck on it for quite sometime now ! Looking forward for your response :-)
